name: test
on: workflow_dispatch

# FOR THIS WORKFLOW TO RUN PROPERLY, MOVE IT TO THE .github/workflows DIRECTORY
jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: rollback
        id: get-rollback-version 
        run: |
          version_rollback=$(echo "" | jq -rc '.spec.resources.helmResources[].values.image.tag')
          echo "version_rollback=$version_rollback" | tee -a $GITHUB_OUTPUT 

      - name: Send rollback event to "DiscoPipeline Events"
        if: steps.get-rollback-version.outputs.version_rollback != ""
        run: echo "hello"


     