name: test
on: workflow_dispatch

# FOR THIS WORKFLOW TO RUN PROPERLY, MOVE IT TO THE .github/workflows DIRECTORY
jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: test
        id: test
        run: |
          sleep 4
          echo "hello"
  second:
    runs-on: ubuntu-latest
    needs: first
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: second
        if: ${{ needs.first.result == 'failure' }}
        id: result
        run: echo "world"

     